export const FETCH_MULTIPLY_REQUEST = 'FETCH_MULTIPLY_REQUEST';
export const FETCH_MULTIPLY_SUCCESS = 'FETCH_MULTIPLY_SUCCESS';
export const FETCH_MULTIPLYLIST_SUCCESS = 'FETCH_MULTIPLYLIST_SUCCESS';
export const FETCH_MULTIPLY_FAILURE = 'FETCH_MULTIPLY_FAILURE';
