export const FETCH_ADD_REQUEST = 'FETCH_ADD_REQUEST';
export const FETCH_ADD_SUCCESS = 'FETCH_ADD_SUCCESS';
export const FETCH_ADDLIST_SUCCESS = 'FETCH_ADDLIST_SUCCESS';
export const FETCH_ADD_FAILURE = 'FETCH_ADD_FAILURE';
