export const FETCH_SUBTRACT_REQUEST = 'FETCH_SUBTRACT_REQUEST';
export const FETCH_SUBTRACT_SUCCESS = 'FETCH_SUBTRACT_SUCCESS';
export const FETCH_SUBTRACTLIST_SUCCESS = 'FETCH_SUBTRACTLIST_SUCCESS';
export const FETCH_SUBTRACT_FAILURE = 'FETCH_SUBTRACT_FAILURE';
