export const FETCH_DIVIDE_REQUEST = 'FETCH_DIVIDE_REQUEST';
export const FETCH_DIVIDE_SUCCESS = 'FETCH_DIVIDE_SUCCESS';
export const FETCH_DIVIDELIST_SUCCESS = 'FETCH_DIVIDELIST_SUCCESS';
export const FETCH_DIVIDE_FAILURE = 'FETCH_DIVIDE_FAILURE';
