export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERSLIST_SUCCESS = 'FETCH_USERSLIST_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const NO_DATA_TEXTFIELDS = 'NO_DATA_TEXTFIELDS';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
